title: local posting ventures
author: "futurewarning"

theme: minima

base_url: /gh-pages-minima-starter

# Minima social links
github_username: futurewarning
telegram: futurewarning
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/routes.md
  - _pages/archive.md

include:
    - _pages

exclude:
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
